name: No Fixme's Check
description: Verify that there are no fixme's in the codebase.

runs:
  using: composite
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Check code contains no FIXME's
      shell: bash {0}
      run: |
        git grep -r --no-color ${case_sensitive} --line-number -e "FIXME" :^.github
        if [[ $? -eq 0 ]]; then
          # if we found any FIXME entries in checked in files, fail on main
          exit 1
        else
          exit 0
        fi
